### ISSUE TITLE
App missing from Play Store

### ISSUE THREAD

**Issue by streeter** [chris84948/open-sky#1]
Hi there! I noticed the app was missing from the Play Store. Did it get taken down? If so should we update the README to say as such?

**Comment by chris84948** [comment]
I almost launched it, but the data wasn't very reliable, so I just cancelled it. I should probably just remove any reference to it being a real product.

**Comment by streeter** [comment]
@chris84948 can one still build it from source and use it? What I really want is a DarkSky UI :/

**Comment by chris84948** [comment]
So it will work, but the data is nowhere near as good as Dark Sky (kind of why I gave up, at least in Minneapolis, it missed a lot of rain/snow). If you build it, you can definitely play with it.

An alternative I've been using is this -

https://lifehacker.com/install-this-dark-sky-android-clone-while-you-can-1844751437

Should until the end of the year I think.

**Comment by chris84948** [comment]
I've also got a release here -

https://github.com/chris84948/open-sky/releases/tag/v1.0

If you want to just give it a try without building.
