### ISSUE TITLE
Need for good app

### ISSUE THREAD

**Issue by madisnormal** [chris84948/open-sky#2]
Hi. Desperately looking for Dark Sky alike app on Android. Would be nice if you continued working on this one.

**Comment by chris84948** [comment]
Thanks for the feedback. I liked making this, but it's the data sources
that are the problem.

I could never find a weather data source that was free and worth anything.

There's an APK build on the releases tab, you could try installing that.
Honestly I can't remember where I left it up. Then you can get an API key
from OpenWeatherMap.

https://github.com/chris84948/open-sky

**Comment by madisnormal** [comment]
Unfortunately it doesn't work. When Providing api key the app throws 402 error.

**Comment by chris84948** [comment]
Sorry, I'm done working on it. If it makes you feel any better, I've never
found a good replacement either.
